// <auto-generated />
namespace NET.W._2018.Korzun._25.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class The5Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(The5Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201812131212333_The 5 Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
