// <auto-generated />
namespace NET.W._2018.Korzun._25.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TheSecondMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TheSecondMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201812131106594_The Second Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
